### ISSUE TITLE
Unicorn 3 support

### ISSUE THREAD

**Issue by kamsar** [BerserkerDotNet/Unicorn.VisualStudio#3] opened 2015-09-21 06:06 UTC
As of 3.0rc2, Unicorn 3 has the APIs the plugin calls for updates built in. You do need to enable `Unicorn.Remote.config.disabled` to turn on the API. It seems to work.

https://github.com/kamsar/Unicorn/commit/dc91cdae1235f3e5d7ec70607cf85b780b5535f0

It does complain that the integration is an older version in the plugin though :)

FWIW, I updated the configuration wiki page with a couple notes on where to find things post-install in VS.

**Comment by kamsar** [comment] 2015-09-21 06:15
I also added a mention of your plugin in the readme: https://github.com/kamsar/Unicorn#unicorn-features

**Comment by BerserkerDotNet** [comment] 2015-09-21 19:33
Wow, I was only planned to move Unicorn.Remote into Unicorn, but woke up in the morning and it is already there :) Super fast, thank you for that!

Issue with "older version" was caused by my silly check for current version of the client.
Since Unicorn.Remote was version 1.1 and Unicorn.dll version 3.0 it was not happy :( 
Should be fixed now, I've made a condition open on the upper bound so it will support 3.0 or above.

Also, I've updated installation instructions and added a check to "Install" button, that will prevent installing Unicorn.Remote if Unicorn 3.0 or above is present in "bin" folder.

**Closed as completed** 2015-09-21 19:34 UTC
